name: String Tips
favicon: null
layout_spectrum: 0.49686808604747057
typography_spectrum: 0.39529110374860466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.01581383077427745
  lightness: 0.12890201504342258
  saturation: 0.9089318425394595
  rhythmicContrast: 0.8682486261241138
purpose: []
